name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Get dependencies
        run: go mod download

      - name: Build amd64
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o bin/notify.exe .

      - name: Build 386
        env:
          GOOS: windows
          GOARCH: 386
        run: go build -o bin/notify-windows-386.exe .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          generate_release_notes: true
          files: |
            bin/notify.exe
            bin/notify-windows-386.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
